#Ce fichier est utilisé pour le test gihub action 

#Je lui donne un nom
name: Integration

#On précise la branche sur lequel il va faire le test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#le nom du test et les étapes qu'il va faire
jobs:
  test-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      #ici on met en secret l'username et le mot de passe grâce à une fonction github
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    #Buil de le docker
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: marinouh/devoir_mk:latest
    
    # 2 tests pour montrer que les tests unitaires fonctionnent
    - name: Test uni premier
      run: echo "Youpi le test unitaire fonctionne !"

    - name: Test uni second
      run: |
        if grep -q "<button.*>.*</button>" index.html; then
          echo "Il y a bien un bouton !"
          exit 0
        else
          echo "Raté"
          exit 1
        fi




