name: Integration

on: 
  push:
    branches:
      - SecondProjetRéussi
  pull_request:
    branches:
      - SecondProjetRéussi

jobs:
  test-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: App/static/templates

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: marinouh/devoir_mk:latest

    - name: Test uni premier
      run: echo "Youpi le test unitaire fonctionne !"

    - name: Test uni second
      run: |
        if grep -q "<button.*>.*</button>" index.html; then
          echo "Il y a bien un bouton !"
          exit 0
        else
          echo "Raté"
          exit 1
        fi




